In [1]:
from archetypes_re2020.utils import bw25_utils
import pandas as pd

12:11:55+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.

In [2]:
p = '/home/thibault.chevilliet@enpc.fr/Documents/Comparaison projets urbains/OUT/2024-08-20_10h45_MC_results.xlsx'

import ast
imp = pd.read_excel(p,sheet_name='Sheet1',index_col=0,header=0)
#On réinterprète les noms de colonnes comme des tuples
tmp = {c : ast.literal_eval(c) for c in imp.columns}
imp = imp.rename(columns=tmp)
#On s'assure que les valeurs du dataframe sont des listes
for l in imp.index :
    for c in imp.columns :
        imp.at[l,c] = ast.literal_eval(imp.at[l,c])

In [3]:
imp.index[0]

"'urban project A' (unit, FR, ('custom process',))"

In [4]:
type(imp.iloc[0,0])

list

In [16]:
df=pd.read_parquet("/home/thibault.chevilliet@enpc.fr/Documents/2601_archetypes_re2020/data/processed/MC_runs/2026-5-9-9h53_MC_runs/scores.parquet")

In [17]:
ind = df["indicator"][0]

In [18]:
df = df.groupby("demand").agg(list).reset_index().set_index("demand")

In [19]:
df

,iteration,indicator,score
demand,,,
bureau,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[ecoinvent-3.11 | EF v3.1 | climate change | g...,"[1271.7522821283767, 1471.689261313125, 1183.9..."
logement_collectif,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[ecoinvent-3.11 | EF v3.1 | climate change | g...,"[1380.6911519465325, 1544.361465136438, 1261.6..."
maison_individuelle_ou_accolée,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[ecoinvent-3.11 | EF v3.1 | climate change | g...,"[1238.3531648266476, 1404.1674698877612, 1124...."

In [20]:
demand_dict = {"bureau" : "'Office building' (m2, FR, ('custom process',))",
"logement_collectif" : "'Multi-family housing' (m2, FR, ('custom process',))",
"maison_individuelle_ou_accolée" : "'Single-family housing' (m2, FR, ('custom process',))"
}

In [21]:
df = df.rename(index=demand_dict)

In [22]:
df

,iteration,indicator,score
demand,,,
"'Office building' (m2, FR, ('custom process',))","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[ecoinvent-3.11 | EF v3.1 | climate change | g...,"[1271.7522821283767, 1471.689261313125, 1183.9..."
"'Multi-family housing' (m2, FR, ('custom process',))","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[ecoinvent-3.11 | EF v3.1 | climate change | g...,"[1380.6911519465325, 1544.361465136438, 1261.6..."
"'Single-family housing' (m2, FR, ('custom process',))","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[ecoinvent-3.11 | EF v3.1 | climate change | g...,"[1238.3531648266476, 1404.1674698877612, 1124...."

In [23]:
df = df.drop(columns=['indicator', 'iteration'])

In [24]:
df = df.rename(columns={"score" : ind})

In [25]:
df

                                                   ecoinvent-3.11 | EF v3.1 | climate change | global warming potential (GWP100)
demand
'Office building' (m2, FR, ('custom process',))     [1271.7522821283767, 1471.689261313125, 1183.9...
'Multi-family housing' (m2, FR, ('custom proces...  [1380.6911519465325, 1544.361465136438, 1261.6...
'Single-family housing' (m2, FR, ('custom proce...  [1238.3531648266476, 1404.1674698877612, 1124....

In [26]:
thres = [1.05,1.1,1.15,1.2,1.25] #seuils à considérer
dis = bw25_utils.discern(thres,df)